#!/usr/bin/env bash

# defaults
user="ghtorrent"
passwd=""
host="localhost"
db="ghtorrent"
out="dump"

usage()
{
  echo "Usage: $0 [-u dbuser ] [-p dbpasswd ]"
  echo "          [-h dbhost] [-d database ] [-o output_dir]"
  echo
  echo "Dump a MySQL database into CSV files per table"
  echo "output_dir must be writable by the mysqld user and must be an absolute path"
  echo "    -u database user (default: $user)"
  echo "    -p database passwd (default: $passwd)"
  echo "    -h database host (default: $host)"
  echo "    -d database (default: $db)"
  echo ""
  echo "    -o intermediate output dir (default: $out)"
}

if [ -z $1 ]
then
  usage
  exit 1
fi

while getopts "u:p:h:d:o:" o
do
  case $o in
  u)  user=$OPTARG ;;
  p)  passwd=$OPTARG ;;
  h)  host=$OPTARG ;;
  d)  db=$OPTARG ;;
  o)  out=$OPTARG ;;
  \?)     echo "Invalid option: -$OPTARG" >&2
    usage
    exit 1
    ;;
  esac
done

echo "`date`: Creating dir $out"
mkdir -p $out

if [ -z $passwd ]; then
  mysql="mysql -u $user -s -h $host -D $db"
else
  mysql="mysql -u $user --password=$passwd -s -h $host -D $db"
fi

tables='issues commits project_commits'

for table in $tables; do
  echo "`date`: Dumping table $table"
  echo "select * into outfile '$out/$table.csv' CHARACTER SET UTF8 FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n' from $table" |$mysql
done
