#!/usr/bin/env bash

# defaults
user="ghtorrent"
passwd=""
host="localhost"
db="ghtorrent"

usage()
{
  echo "Usage: $0 [-u dbuser ] [-p dbpasswd ] [-h dbhost] [-d database ] dump_dir"
  echo
  echo "Restore a database from CSV and SQL files in dump_dir"
  echo "    -u database user (default: $user)"
  echo "    -p database passwd (default: $passwd)"
  echo "    -h database host (default: $host)"
  echo "    -d database to restore to. Must exist. (default: $db)"
}

if [ -z $1 ]
then
  usage
  exit 1
fi

while getopts "u:p:h:d:" o
do
  case $o in
  u)  user=$OPTARG ;;
  p)  passwd=$OPTARG ;;
  h)  host=$OPTARG ;;
  d)  db=$OPTARG ;;
  \?)     echo "Invalid option: -$OPTARG" >&2
    usage
    exit 1
    ;;
  esac
done

# Setup PostgreSQL command line
if ! [ -z $passwd ]; then
  export PGPASSWORD=$passwd
fi

psql="psql -U $user -t -q -h $host -d $db"

shift $(expr $OPTIND - 1)
dumpDir=$1

if [ ! -e $dumpDir ]; then
  echo "Cannot find directory to restore from"
  exit 1
fi

# Convert to full path
dumpDir="`pwd`/$dumpDir"

if [ ! -e $dumpDir/pg_schema.sql ]; then
  echo "Cannot find $dumpDir/pg_schema.sql to create DB schema"
  exit 1
fi

# 1. Create db schema
echo "`date` Creating the DB schema"
cat $dumpDir/pg_schema.sql | $psql

# 1.5 some commits data comtain invalid datetime values, this step will replace those values with earlist unix time
sed -i -e 's/0000-00-00 00:00:00/1970-01-02 00:00:00/' commits.csv

# 2. Restore CSV files with disabled FK checks
for f in $dumpDir/*.csv ; do
  table=`basename $f|cut -f1 -d'.'`
  echo "`date` Restoring table $table"
  echo "COPY $table FROM '$f' WITH (FORMAT 'csv', QUOTE E'\"', ESCAPE '\', NULL '\N');" | $psql || exit 1
done

# 3. Reset sequences
if [ ! -e $dumpDir/pg_reset_sequences.sql ]; then
  echo "Cannot find $dumpDir/pg_reset_sequences.sql to create DB indexes and foreign keys"
  exit 1
fi

echo "`date` Resetting sequences"
cat $dumpDir/pg_reset_sequences.sql |
while read idx; do
  echo "`date` $idx"
  echo $idx | $psql || exit 1
done

# 4. Create indexes
if [ ! -e $dumpDir/pg_indexes_and_foreign_keys.sql ]; then
  echo "Cannot find $dumpDir/pg_indexes_and_foreign_keys.sql to create DB indexes and foreign keys"
  exit 1
fi

echo "`date` Creating indexes"
cat $dumpDir/pg_indexes_and_foreign_keys.sql |
while read idx; do
  echo "`date` $idx"
  echo $idx | $psql || exit 1
done

#: ft=bash
