#!/usr/bin/env bash

# defaults
user="ghtorrent"
passwd=""
host="localhost"
db="ghtorrent"
engine="MyISAM"

usage()
{
  cat <<EOF 1>&2
Usage: $0 [-u dbuser ] [-p dbpasswd ] [-h dbhost] [-d database ] dump_dir

Restore a database from CSV and SQL files in dump_dir
    -u database user (default: $user)
    -p database passwd (default: $passwd)
    -h database host (default: $host)
    -d database to restore to. Must exist. (default: $db)
    -e db engine: MyISAM for fast import and querying speed
                  InnoDB for normal operations (default: $engine)
EOF
}

if [ -z $1 ]
then
  usage
  exit 1
fi

while getopts "u:p:h:d:e:" o
do
  case $o in
  u)  user=$OPTARG ;;
  p)  passwd=$OPTARG ;;
  h)  host=$OPTARG ;;
  d)  db=$OPTARG ;;
  e)  engine=$OPTARG ;;
  \?)     echo "Invalid option: -$OPTARG" >&2
    usage
    exit 1
    ;;
  esac
done

# Setup MySQL command line
if [ -z $passwd ]; then
  mysql="mysql -u $user -s -h $host -D $db"
else
  mysql="mysql -u $user --password=$passwd -s -h $host -D $db"
fi

shift $(expr $OPTIND - 1)
dumpDir=$1

if [ ! -d $dumpDir ]; then
  echo "Cannot find directory to restore from" 1>&2
  exit 1
fi

# Convert to full path
dumpDir="`pwd`/$dumpDir"

if [ ! -r $dumpDir/schema.sql ]; then
  echo "Cannot read $dumpDir/schema.sql to create DB schema" 1>&2
  exit 1
fi

# 1. Create db schema
echo "`date` Creating the DB schema"
sed -e "s/\`ghtorrent\`/\`$db\`/" $dumpDir/schema.sql |
sed -e "s/InnoDB/$engine/"|
grep -v "^--" |
$mysql

# 2. Restore CSV files with disabled FK checks
for f in $dumpDir/*.csv ; do
  table=`basename $f|cut -f1 -d'.'`
  echo "`date` Restoring table $table"
  echo "SET foreign_key_checks = 0; LOAD DATA LOCAL INFILE '$f' INTO TABLE $table CHARACTER SET UTF8 FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n';" |$mysql || exit 1
done

# 3. Create indexes
if [ ! -r $dumpDir/indexes.sql ]; then
  echo "Cannot read $dumpDir/indexes.sql to create DB indexes" 1>&2
  exit 1
fi

echo "`date` Creating indexes"
sed -e "s/\`ghtorrent\`/\`$db\`/" $dumpDir/indexes.sql |
grep -v "^--" |
while read idx; do
  echo "`date` $idx"
  echo $idx | $mysql || exit 1
done

#: ft=bash
