#!/usr/bin/env bash

# defaults
user="ghtorrent"
passwd=""
host="localhost"
db="ghtorrent"
engine="MyISAM"

usage()
{
  echo "Usage: $0 [-u dbuser ] [-p dbpasswd ] [-h dbhost] [-d database ] dump_dir"
  echo
  echo "Restore a database from CSV and SQL files in dump_dir"
  echo "    -u database user (default: $user)"
  echo "    -p database passwd (default: $passwd)"
  echo "    -h database host (default: $host)"
  echo "    -d database to restore to. Must exist. (default: $db)"
  echo "    -e db engine: MyISAM for fast import and querying speed"
  echo "                  InnoDB for normal operations (default: $engine)"
  echo "    -c create the database and user"
}

if [ -z $1 ]
then
  usage
  exit 1
fi

while getopts "u:p:h:d:e:c" o
do
  case $o in
  u)  user=$OPTARG ;;
  p)  passwd=$OPTARG ; set_passwd="IDENTIFIED BY '$passwd'" ;;
  h)  host=$OPTARG ;;
  d)  db=$OPTARG ;;
  e)  engine=$OPTARG ;;
  c)  create=1 ;;
  \?)     echo "Invalid option: -$OPTARG" >&2
    usage
    exit 1
    ;;
  esac
done

# Create the database and user if requested
if [ -n "$create_db" ] ; then
  echo "When prompted, enter the database's root password."
  cat <<EOF |
  CREATE DATABASE IF NOT EXISTS $db;
  CREATE USER IF NOT EXISTS '$user'@'$host' $set_passwd;
  GRANT ALL PRIVILEGES ON $db.* TO '$user'@'$host';
  FLUSH PRIVILEGES;
EOF
  mysql -u root -p
fi


# Setup MySQL command line
if [ -z $passwd ]; then
  mysql="mysql -u $user -s -h $host -D $db"
else
  mysql="mysql -u $user --password=$passwd -s -h $host -D $db"
fi

shift $(expr $OPTIND - 1)
dumpDir=$1

if [ ! -e $dumpDir ]; then
  echo "Cannot find directory to restore from"
  exit 1
fi

# Convert to full path
dumpDir="`pwd`/$dumpDir"

if [ ! -e $dumpDir/schema.sql ]; then
  echo "Cannot find $dumpDir/schema.sql to create DB schema"
  exit 1
fi

# 1. Create db schema
echo "`date` Creating the DB schema"
cat $dumpDir/schema.sql |
sed -e "s/\`ghtorrent\`/\`$db\`/" |
sed -e "s/InnoDB/$engine/"|
grep -v "^--" |
$mysql

# 2. Restore CSV files with disabled FK checks
for f in $dumpDir/*.csv ; do
  table=`basename $f|cut -f1 -d'.'`
  echo "`date` Restoring table $table"
  echo "SET foreign_key_checks = 0; LOAD DATA LOCAL INFILE '$f' INTO TABLE $table CHARACTER SET UTF8 FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n';" |$mysql || exit 1
done

# 3. Create indexes
if [ ! -e $dumpDir/indexes.sql ]; then
  echo "Cannot find $dumpDir/indexes.sql to create DB indexes"
  exit 1
fi

echo "`date` Creating indexes"
cat $dumpDir/indexes.sql |
sed -e "s/\`ghtorrent\`/\`$db\`/" |
grep -v "^--" |
while read idx; do
  echo "`date` $idx"
  echo $idx | $mysql || exit 1
done

# Restrict database permissions
if [ -n "$create_db" ] ; then
  echo "When prompted, enter the database's root password."
  cat <<EOF |
  REVOKE ALL ON $db.* FROM '$user'@'$host';
  GRANT SELECT ON $db.* TO '$user'@'$host';
  FLUSH PRIVILEGES;
EOF
  mysql -u root -p
fi


#: ft=bash
