#!/usr/bin/env bash

# defaults
user="ghtorrent"
passwd=""
host="localhost"
db="ghtorrent"
out="dump"
skipArchive=false
skipTables=""

ts=`date +%Y-%m-%d`
dumpName=`echo mysql-$ts.tar.gz`

usage()
{
  echo "Usage: $0 [-u dbuser ] [-p dbpasswd ]"
  echo "          [-h dbhost] [-d database ] [-o output_dir]"
  echo "          [-a archive_name ] [-f skip_tables] [-c skip_archive]"
  echo
  echo "Dump a MySQL database into CSV files per table"
  echo "output_dir must be writable by the mysqld user and must be an absolute path"
  echo "    -u database user (default: $user)"
  echo "    -p database passwd (default: $passwd)"
  echo "    -h database host (default: $host)"
  echo "    -d database (default: $db)"
  echo ""
  echo "    -o intermediate output dir (default: $out)"
  echo "    -f file with table names to skip (default: $skipTables)"
  echo "    -c skip creating .tar.gz archive (default: $skipArchive)"
  echo "    -a archive name (default: $dumpName)"
}

if [ -z $1 ]
then
  usage
  exit 1
fi

while getopts "u:p:h:d:o:cf:" o
do
  case $o in
  u)  user=$OPTARG ;;
  p)  passwd=$OPTARG ;;
  h)  host=$OPTARG ;;
  d)  db=$OPTARG ;;
  o)  out=$OPTARG ;;
  a)  dumpName=$OPTARG ;;
  c)  skipArchive=true ;;
  f)  skipTables=$OPTARG ;;
  \?)     echo "Invalid option: -$OPTARG" >&2
    usage
    exit 1
    ;;
  esac
done

echo "`date` Creating dir $out"
mkdir -p $out

if [ -z $passwd ]; then
  mysql="mysql -u $user -s -h $host -D $db"
else
  mysql="mysql -u $user --password=$passwd -s -h $host -D $db"
fi

tables=`echo "show tables" | $mysql`

for table in $tables; do
  if [ ! -z $skipTables ] && [ `grep ^$table$ $skipTables` ]; then
    echo "`date`: Skipping table $table"
  elif [ $table == 'users' ]; then
    echo "`date`: Dumping table users"
    echo "select id,login,company,created_at,type,fake,deleted,lat,country_code,state,city,location into outfile '$out/users.csv' CHARACTER SET UTF8 FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n' from users" |$mysql || exit 1
    echo "select login,name,email into outfile '$out/users-private.csv' CHARACTER SET UTF8 FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n' from users" |$mysql || exit 1
  else
    echo "`date`: Dumping table $table"
    echo "select * into outfile '$out/$table.csv' CHARACTER SET UTF8 FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '\"' LINES TERMINATED BY '\n' from $table" |$mysql || exit 1
  fi
done

echo "`date` Copying schema and index files"
curl "https://raw.githubusercontent.com/gousiosg/github-mirror/master/sql/indexes.sql" > $out/indexes.sql
curl "https://raw.githubusercontent.com/gousiosg/github-mirror/master/sql/schema.sql" > $out/schema.sql
curl "https://raw.githubusercontent.com/gousiosg/github-mirror/master/sql/ght-restore-mysql" > $out/ght-restore-mysql
curl "https://raw.githubusercontent.com/gousiosg/github-mirror/master/sql/README.md" > $out/README.md
curl "https://raw.githubusercontent.com/gousiosg/github-mirror/master/sql/ORDER" > $out/ORDER

if [ $skipArchive = false ]; then
  echo "`date` Creating archive $dumpName"
  cd `dirname $out`
  tar zcvf $dumpName --exclude='users-private.csv' `basename $out` || exit 1
  gzip $out/users-private.csv
  mv $out/users-private.csv.gz .
  rm -R $out
fi

#: ft=bash
