CREATE UNIQUE INDEX `login` ON `ghtorrent`.`users` (`login` ASC)  COMMENT '';
CREATE UNIQUE INDEX `name` ON `ghtorrent`.`projects` (`name` ASC, `owner_id` ASC)  COMMENT '';
CREATE INDEX `owner_id` ON `ghtorrent`.`projects` (`owner_id` ASC)  COMMENT '';
CREATE INDEX `forked_from` ON `ghtorrent`.`projects` (`forked_from` ASC)  COMMENT '';
CREATE UNIQUE INDEX `sha` ON `ghtorrent`.`commits` (`sha` ASC)  COMMENT '';
CREATE INDEX `author_id` ON `ghtorrent`.`commits` (`author_id` ASC)  COMMENT '';
CREATE INDEX `committer_id` ON `ghtorrent`.`commits` (`committer_id` ASC)  COMMENT '';
CREATE INDEX `project_id` ON `ghtorrent`.`commits` (`project_id` ASC)  COMMENT '';
CREATE UNIQUE INDEX `comment_id` ON `ghtorrent`.`commit_comments` (`comment_id` ASC)  COMMENT '';
CREATE INDEX `commit_id` ON `ghtorrent`.`commit_comments` (`commit_id` ASC)  COMMENT '';
CREATE INDEX `user_id` ON `ghtorrent`.`commit_comments` (`user_id` ASC)  COMMENT '';
CREATE INDEX `parent_id` ON `ghtorrent`.`commit_parents` (`parent_id` ASC)  COMMENT '';
CREATE INDEX `follower_id` ON `ghtorrent`.`followers` (`follower_id` ASC)  COMMENT '';
CREATE UNIQUE INDEX `pullreq_id` ON `ghtorrent`.`pull_requests` (`pullreq_id` ASC, `base_repo_id` ASC)  COMMENT '';
CREATE INDEX `head_repo_id` ON `ghtorrent`.`pull_requests` (`head_repo_id` ASC)  COMMENT '';
CREATE INDEX `base_repo_id` ON `ghtorrent`.`pull_requests` (`base_repo_id` ASC)  COMMENT '';
CREATE INDEX `head_commit_id` ON `ghtorrent`.`pull_requests` (`head_commit_id` ASC)  COMMENT '';
CREATE INDEX `base_commit_id` ON `ghtorrent`.`pull_requests` (`base_commit_id` ASC)  COMMENT '';
CREATE INDEX `repo_id` ON `ghtorrent`.`issues` (`repo_id` ASC)  COMMENT '';
CREATE INDEX `reporter_id` ON `ghtorrent`.`issues` (`reporter_id` ASC)  COMMENT '';
CREATE INDEX `assignee_id` ON `ghtorrent`.`issues` (`assignee_id` ASC)  COMMENT '';
CREATE INDEX `pull_request_id` ON `ghtorrent`.`issues` (`pull_request_id` ASC)  COMMENT '';
CREATE INDEX `issue_id` ON `ghtorrent`.`issue_comments` (`issue_id` ASC)  COMMENT '';
CREATE INDEX `user_id` ON `ghtorrent`.`issue_comments` (`user_id` ASC)  COMMENT '';
CREATE INDEX `issue_id` ON `ghtorrent`.`issue_events` (`issue_id` ASC)  COMMENT '';
CREATE INDEX `actor_id` ON `ghtorrent`.`issue_events` (`actor_id` ASC)  COMMENT '';
CREATE INDEX `repo_id` ON `ghtorrent`.`repo_labels` (`repo_id` ASC)  COMMENT '';
CREATE INDEX `label_id` ON `ghtorrent`.`issue_labels` (`label_id` ASC)  COMMENT '';
CREATE INDEX `user_id` ON `ghtorrent`.`organization_members` (`user_id` ASC)  COMMENT '';
CREATE INDEX `commit_id` ON `ghtorrent`.`project_commits` (`commit_id` ASC)  COMMENT '';
CREATE INDEX `user_id` ON `ghtorrent`.`project_members` (`user_id` ASC)  COMMENT '';
CREATE INDEX `pull_request_id` ON `ghtorrent`.`pull_request_comments` (`pull_request_id` ASC)  COMMENT '';
CREATE INDEX `user_id` ON `ghtorrent`.`pull_request_comments` (`user_id` ASC)  COMMENT '';
CREATE INDEX `commit_id` ON `ghtorrent`.`pull_request_comments` (`commit_id` ASC)  COMMENT '';
CREATE INDEX `commit_id` ON `ghtorrent`.`pull_request_commits` (`commit_id` ASC)  COMMENT '';
CREATE INDEX `pull_request_id` ON `ghtorrent`.`pull_request_history` (`pull_request_id` ASC)  COMMENT '';
CREATE INDEX `actor_id` ON `ghtorrent`.`pull_request_history` (`actor_id` ASC)  COMMENT '';
CREATE INDEX `repo_id` ON `ghtorrent`.`repo_milestones` (`repo_id` ASC)  COMMENT '';
CREATE INDEX `user_id` ON `ghtorrent`.`watchers` (`user_id` ASC)  COMMENT '';
